# Generated by Django 3.2.7 on 2021-09-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210907_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='headimg',
            new_name='headImg',
        ),
    ]
